export const Icons = [
  // ===== EMOTIONS =====
  { id: 1, key: 'smile', value: '😊', category: 'emotion', priority: true },
  { id: 2, key: 'laugh', value: '😂', category: 'emotion', priority: true },
  { id: 3, key: 'love', value: '😍', category: 'emotion', priority: true },
  { id: 4, key: 'cry', value: '😢', category: 'emotion' },
  { id: 5, key: 'angry', value: '😡', category: 'emotion' },
  { id: 6, key: 'sleepy', value: '😴', category: 'emotion' },
  { id: 7, key: 'thinking', value: '🤔', category: 'emotion' },
  { id: 8, key: 'cool', value: '😎', category: 'emotion' },
  { id: 9, key: 'party', value: '🥳', category: 'emotion', priority: true },
  { id: 10, key: 'sob', value: '😭', category: 'emotion', priority: true },
  { id: 11, key: 'scream', value: '😱', category: 'emotion' },
  { id: 12, key: 'mindblown', value: '🤯', category: 'emotion' },
  { id: 13, key: 'angel', value: '😇', category: 'emotion' },
  { id: 14, key: 'pleading', value: '🥺', category: 'emotion', priority: true },
  { id: 15, key: 'frustrated', value: '😤', category: 'emotion' },

  // ===== ANIMALS =====
  { id: 16, key: 'dog', value: '🐶', category: 'animal' },
  { id: 17, key: 'cat', value: '🐱', category: 'animal' },
  { id: 18, key: 'lion', value: '🦁', category: 'animal' },
  { id: 19, key: 'panda', value: '🐼', category: 'animal' },
  { id: 20, key: 'fox', value: '🦊', category: 'animal' },
  { id: 21, key: 'giraffe', value: '🦒', category: 'animal' },
  { id: 22, key: 'kangaroo', value: '🦘', category: 'animal' },
  { id: 23, key: 'parrot', value: '🦜', category: 'animal' },
  { id: 24, key: 'swan', value: '🦢', category: 'animal' },
  { id: 25, key: 'butterfly', value: '🦋', category: 'animal' },
  { id: 26, key: 'turtle', value: '🐢', category: 'animal' },
  { id: 27, key: 'octopus', value: '🐙', category: 'animal' },
  { id: 28, key: 'shark', value: '🦈', category: 'animal' },
  { id: 29, key: 'owl', value: '🦉', category: 'animal' },
  { id: 30, key: 'unicorn', value: '🦄', category: 'animal' },

  // ===== FOOD =====
  { id: 31, key: 'pizza', value: '🍕', category: 'food', priority: true },
  { id: 32, key: 'burger', value: '🍔', category: 'food', priority: true },
  { id: 33, key: 'noodles', value: '🍜', category: 'food' },
  { id: 34, key: 'sushi', value: '🍣', category: 'food' },
  { id: 35, key: 'bento', value: '🍱', category: 'food' },
  { id: 36, key: 'riceball', value: '🍙', category: 'food' },
  { id: 37, key: 'rice', value: '🍚', category: 'food' },
  { id: 38, key: 'cracker', value: '🍘', category: 'food' },
  { id: 39, key: 'fishcake', value: '🍥', category: 'food' },
  { id: 40, key: 'dumpling', value: '🥟', category: 'food' },
  { id: 41, key: 'shrimp', value: '🍤', category: 'food' },
  { id: 42, key: 'chicken', value: '🍗', category: 'food' },
  { id: 43, key: 'meat', value: '🍖', category: 'food' },
  { id: 44, key: 'steak', value: '🥩', category: 'food' },
  { id: 45, key: 'bacon', value: '🥓', category: 'food' },

  // ===== ACTIVITIES =====
  {
    id: 46,
    key: 'football',
    value: '⚽',
    category: 'activity',
    priority: true,
  },
  { id: 47, key: 'gaming', value: '🎮', category: 'activity', priority: true },
  { id: 48, key: 'art', value: '🎨', category: 'activity' },
  { id: 49, key: 'theater', value: '🎭', category: 'activity' },
  { id: 50, key: 'circus', value: '🎪', category: 'activity' },
  { id: 51, key: 'target', value: '🎯', category: 'activity' },
  { id: 52, key: 'dice', value: '🎲', category: 'activity' },
  { id: 53, key: 'guitar', value: '🎸', category: 'activity' },
  { id: 54, key: 'piano', value: '🎹', category: 'activity' },
  { id: 55, key: 'trumpet', value: '🎺', category: 'activity' },
  { id: 56, key: 'violin', value: '🎻', category: 'activity' },
  { id: 57, key: 'movie', value: '🎬', category: 'activity' },

  // ===== SYMBOLS =====
  { id: 58, key: 'heart', value: '❤️', category: 'symbol', priority: true },
  { id: 59, key: 'star', value: '⭐', category: 'symbol' },
  { id: 60, key: 'hundred', value: '💯', category: 'symbol' },
  { id: 61, key: 'sparkles', value: '✨', category: 'symbol' },
  { id: 62, key: 'glow', value: '🌟', category: 'symbol' },
  { id: 63, key: 'dizzy', value: '💫', category: 'symbol' },
  { id: 64, key: 'boom', value: '💥', category: 'symbol' },
  { id: 65, key: 'fire', value: '🔥', category: 'symbol', priority: true },
  { id: 66, key: 'strong', value: '💪', category: 'symbol' },
  { id: 67, key: 'pray', value: '🙏', category: 'symbol' },
  { id: 68, key: 'clap', value: '👏', category: 'symbol', priority: true },
  { id: 69, key: 'thumbsup', value: '👍', category: 'symbol', priority: true },
  { id: 70, key: 'partyPopper', value: '🎉', category: 'symbol' },
  { id: 71, key: 'trophy', value: '🏆', category: 'symbol' },
  { id: 72, key: 'gem', value: '💎', category: 'symbol' },
]
